from app.services.part2a.admission_service import AdmissionService
from app.services.part2a.student_extended_service import StudentExtendedService
from app.services.part2a.class_management_service import ClassManagementService
from app.services.part2a.subject_service import SubjectService
from app.services.part2a.timetable_service import TimetableService
from app.services.part2a.attendance_service import AttendanceService
from app.services.part2a.promotion_service import PromotionService
from app.services.part2a.transfer_service import TransferService
from app.services.part2a.id_card_service import IDCardService
from app.services.part2a.bulk_service import BulkService
from app.services.part2a.report_service import ReportService
