# Generated by Django 4.2.9 on 2026-05-16 14:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('reason', models.TextField()),
                ('block_type', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto-blocked')], default='auto', max_length=10)),
                ('duration', models.CharField(choices=[('temporary', 'Temporary'), ('permanent', 'Permanent')], default='temporary', max_length=10)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hit_count', models.IntegerField(default=0, help_text='How many times this IP tried after being blocked')),
            ],
            options={
                'db_table': 'blocked_ips',
                'ordering': ['-blocked_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField(default=False)),
                ('failure_reason', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'login_attempts',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAnalystProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analyst_id', models.CharField(max_length=20, unique=True)),
                ('clearance_level', models.IntegerField(default=1, help_text='1=Junior, 2=Senior, 3=Lead')),
                ('can_block_ips', models.BooleanField(default=True)),
                ('can_lock_accounts', models.BooleanField(default=True)),
                ('can_view_payloads', models.BooleanField(default=False, help_text='Can see raw attack payloads')),
                ('on_duty', models.BooleanField(default=False)),
                ('alert_email', models.EmailField(blank=True, max_length=254)),
                ('alert_phone', models.CharField(blank=True, max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'security_analyst_profiles',
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('BRUTE_FORCE', 'Brute Force Attack'), ('SQL_INJECTION', 'SQL Injection Attempt'), ('XSS_ATTEMPT', 'XSS Attempt'), ('CSRF_VIOLATION', 'CSRF Violation'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Access'), ('PRIVILEGE_ESCALATION', 'Privilege Escalation Attempt'), ('SUSPICIOUS_LOGIN', 'Suspicious Login'), ('MULTIPLE_FAILED_LOGIN', 'Multiple Failed Logins'), ('UNUSUAL_LOCATION', 'Unusual Location Login'), ('RATE_LIMIT_EXCEEDED', 'Rate Limit Exceeded'), ('FILE_UPLOAD_THREAT', 'Malicious File Upload Attempt'), ('PATH_TRAVERSAL', 'Path Traversal Attempt'), ('COMMAND_INJECTION', 'Command Injection Attempt'), ('DATA_EXFILTRATION', 'Possible Data Exfiltration'), ('ACCOUNT_LOCKOUT', 'Account Locked Out'), ('SESSION_HIJACKING', 'Session Hijacking Attempt'), ('DOS_ATTACK', 'DoS/DDoS Attack'), ('MALICIOUS_FILE', 'Malicious File Detected'), ('PERMISSION_DENIED', 'Permission Denied'), ('INFO', 'Information')], max_length=30)),
                ('threat_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewing', 'Reviewing'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='open', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('raw_payload', models.TextField(blank=True, help_text='Sanitized request payload')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('action_taken', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('analyst_notes', models.TextField(blank=True)),
                ('ip_blocked', models.BooleanField(default=False)),
                ('user_locked', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'security_events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SecurityPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('max_login_attempts', models.IntegerField(default=5)),
                ('lockout_duration_minutes', models.IntegerField(default=30)),
                ('max_requests_per_minute', models.IntegerField(default=60)),
                ('max_requests_per_hour', models.IntegerField(default=1000)),
                ('session_timeout_minutes', models.IntegerField(default=60)),
                ('max_sessions_per_user', models.IntegerField(default=3)),
                ('allowed_file_extensions', models.JSONField(default=list)),
                ('max_file_size_mb', models.IntegerField(default=10)),
                ('scan_uploads_for_malware', models.BooleanField(default=True)),
                ('auto_block_on_brute_force', models.BooleanField(default=True)),
                ('auto_block_on_sql_inject', models.BooleanField(default=True)),
                ('auto_block_on_xss', models.BooleanField(default=True)),
                ('notify_analyst_on_critical', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'security_policies',
            },
        ),
        migrations.CreateModel(
            name='SystemHealthSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active_users', models.IntegerField(default=0)),
                ('requests_per_minute', models.FloatField(default=0)),
                ('error_rate', models.FloatField(default=0, help_text='Percentage of 4xx/5xx responses')),
                ('blocked_ips_count', models.IntegerField(default=0)),
                ('open_threats_count', models.IntegerField(default=0)),
                ('cpu_usage', models.FloatField(default=0)),
                ('memory_usage', models.FloatField(default=0)),
                ('db_connections', models.IntegerField(default=0)),
                ('avg_response_ms', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'system_health_snapshots',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('login_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('logout_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_sessions',
                'ordering': ['-login_at'],
            },
        ),
    ]
