# Generated by Django 4.2.9 on 2026-05-30 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("security", "0003_add_firewall_rule"),
    ]

    operations = [
        migrations.CreateModel(
            name="IPReputationScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(db_index=True, unique=True),
                ),
                (
                    "score",
                    models.IntegerField(default=0, help_text="0=clean, 100=malicious"),
                ),
                ("abuseipdb_score", models.IntegerField(default=0)),
                ("virustotal_score", models.IntegerField(default=0)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("isp", models.CharField(blank=True, max_length=200)),
                ("is_vpn", models.BooleanField(default=False)),
                ("is_tor", models.BooleanField(default=False)),
                ("last_checked", models.DateTimeField(auto_now=True)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "ip_reputation_scores",
            },
        ),
        migrations.AlterField(
            model_name="firewallrule",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.CreateModel(
            name="UnblockAppeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Contact email of the person appealing",
                        max_length=254,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("reviewer_note", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "blocked_ip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appeals",
                        to="security.blockedip",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_appeals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "unblock_appeals",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="CIDRBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cidr",
                    models.CharField(
                        help_text="e.g. 192.168.0.0/16", max_length=50, unique=True
                    ),
                ),
                ("reason", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blocked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cidr_blocks",
            },
        ),
    ]
