# Generated by Django 4.2.9 on 2026-05-16 14:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('WAEC', 'WAEC SSCE Result'), ('NECO', 'NECO SSCE Result'), ('JAMB', 'JAMB Result'), ('BIRTH_CERT', 'Birth Certificate'), ('LGC', 'Local Government Certificate'), ('NYSC', 'NYSC Certificate'), ('DEGREE', 'University Degree'), ('OTHER', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='credentials/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_hash', models.CharField(blank=True, help_text='SHA-256 hash for tamper detection', max_length=64)),
                ('forgery_risk_score', models.IntegerField(default=0, help_text='0=clean, 100=definitely forged')),
                ('ai_verdict', models.CharField(blank=True, max_length=20)),
                ('ai_findings', models.JSONField(blank=True, default=dict, help_text='Detailed AI analysis findings')),
                ('extracted_text', models.TextField(blank=True, help_text='OCR extracted text')),
                ('external_verified', models.BooleanField(default=False)),
                ('external_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Under Review'), ('authentic', 'Verified Authentic'), ('suspicious', 'Suspicious'), ('forged', 'Forged — Rejected'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'credentials',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
