# Generated by Django 4.2.9 on 2026-05-16 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_initial'),
        ('students', '0001_initial'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='courses.course'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='invigilator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invigilated_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.academicsession'),
        ),
        migrations.AddField(
            model_name='examclearance',
            name='cleared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examclearance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.academicsession'),
        ),
        migrations.AddField(
            model_name='examclearance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_clearances', to='students.studentprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='examschedule',
            unique_together={('course', 'session', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='examclearance',
            unique_together={('student', 'session', 'semester')},
        ),
    ]
