# Generated by Django 4.2.9 on 2026-05-16 14:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Faculties',
                'db_table': 'faculties',
            },
        ),
        migrations.CreateModel(
            name='LecturerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(blank=True, help_text='e.g. Dr., Prof.', max_length=50)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('specialization_area', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'lecturer_profiles',
            },
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship', models.CharField(default='Parent', max_length=50)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'parent_profiles',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('min_entry_requirements', models.JSONField(default=dict, help_text="e.g. {'subjects':['Math','English'],'min_grade':'C'}")),
            ],
            options={
                'db_table': 'specializations',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matric_number', models.CharField(max_length=20, unique=True)),
                ('level', models.IntegerField(choices=[(100, '100L'), (200, '200L'), (300, '300L'), (400, '400L'), (500, '500L')], default=100)),
                ('admission_year', models.IntegerField()),
                ('admission_session', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('graduated', 'Graduated'), ('deferred', 'Deferred'), ('withdrawn', 'Withdrawn')], default='active', max_length=20)),
                ('cgpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('total_credit_units_earned', models.IntegerField(default=0)),
                ('jamb_score', models.IntegerField(blank=True, null=True)),
                ('jamb_reg_number', models.CharField(blank=True, max_length=20)),
                ('o_level_result', models.JSONField(blank=True, default=dict)),
                ('state_of_origin', models.CharField(blank=True, max_length=100)),
                ('lga_of_origin', models.CharField(blank=True, max_length=100)),
                ('home_address', models.TextField(blank=True)),
                ('next_of_kin', models.CharField(blank=True, max_length=200)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=20)),
                ('next_of_kin_relationship', models.CharField(blank=True, max_length=50)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('genotype', models.CharField(blank=True, max_length=5)),
                ('medical_conditions', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.department')),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.specialization')),
            ],
            options={
                'db_table': 'student_profiles',
                'ordering': ['matric_number'],
            },
        ),
    ]
