# Generated by Django 6.0.7 on 2026-07-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='numeric_id',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='numeric_id',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='reg_dept_id',
            field=models.CharField(blank=True, db_index=True, max_length=2),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='reg_entry_level',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='reg_faculty_id',
            field=models.CharField(blank=True, db_index=True, max_length=2),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='reg_sequence',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='reg_year',
            field=models.CharField(blank=True, db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='matric_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
