# Generated by Django 4.2.9 on 2026-05-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportsnapshot",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Optional: stored output file (PDF/CSV/XLSX)",
                null=True,
                upload_to="reports/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="reportsnapshot",
            name="parameters",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="The filter/date-range parameters used to produce this report",
            ),
        ),
        migrations.AlterField(
            model_name="reportsnapshot",
            name="row_count",
            field=models.IntegerField(
                default=0, help_text="Number of data rows in this report snapshot"
            ),
        ),
    ]
