# Generated by Django 4.2.9 on 2026-05-16 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseassignment',
            name='lecturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.academicsession'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='students.department'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='courses.enrollment'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course', 'session', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='courseassignment',
            unique_together={('course', 'session', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('enrollment', 'date')},
        ),
    ]
