# Generated by Django 4.2.9 on 2026-07-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatroom_admins_chatroom_avatar_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('course', 'Course'), ('direct', 'Direct'), ('support', 'Support'), ('general', 'General'), ('group', 'Group'), ('ai', 'AI')], default='general', max_length=20),
        ),
    ]
