# Generated by Django 4.2.9 on 2026-05-16 14:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offer_number', models.CharField(max_length=30, unique=True)),
                ('programme', models.CharField(max_length=10)),
                ('entry_level', models.IntegerField(default=100)),
                ('session', models.CharField(max_length=20)),
                ('scholarship', models.BooleanField(default=False)),
                ('scholarship_details', models.TextField(blank=True)),
                ('special_conditions', models.TextField(blank=True, help_text='e.g. Must submit NYSC certificate before resumption')),
                ('acceptance_fee', models.DecimalField(decimal_places=2, default=25000, max_digits=10)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('email_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'admission_offers',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_name', models.CharField(help_text='e.g. 2025/2026', max_length=20, unique=True)),
                ('open_date', models.DateField()),
                ('close_date', models.DateField()),
                ('offer_deadline', models.DateField(help_text='Deadline for applicants to accept/decline offer')),
                ('is_active', models.BooleanField(default=False)),
                ('total_slots', models.IntegerField(default=0)),
                ('filled_slots', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admission_sessions',
                'ordering': ['-session_name'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_no', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('screening', 'Under Screening'), ('shortlisted', 'Shortlisted'), ('offered', 'Offer Sent'), ('accepted', 'Offer Accepted'), ('declined', 'Offer Declined'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted'), ('expired', 'Offer Expired'), ('enrolled', 'Enrolled')], default='submitted', max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('state_of_origin', models.CharField(max_length=100)),
                ('lga', models.CharField(max_length=100)),
                ('nationality', models.CharField(default='Nigerian', max_length=100)),
                ('home_address', models.TextField()),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='admissions/photos/')),
                ('programme', models.CharField(choices=[('BSC', 'Bachelor of Science (B.Sc.)'), ('BEng', 'Bachelor of Engineering (B.Eng.)'), ('BA', 'Bachelor of Arts (B.A.)'), ('BEd', 'Bachelor of Education (B.Ed.)'), ('LLB', 'Bachelor of Laws (LLB)'), ('MBBS', 'Medicine (MBBS)')], default='BSC', max_length=10)),
                ('entry_type', models.CharField(choices=[('UTME', 'UTME/Post-UTME'), ('DE', 'Direct Entry'), ('TRANSFER', 'Inter-University Transfer')], default='UTME', max_length=10)),
                ('jamb_reg_no', models.CharField(max_length=20)),
                ('jamb_score', models.IntegerField()),
                ('jamb_year', models.IntegerField()),
                ('post_utme_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('aggregate_score', models.DecimalField(blank=True, decimal_places=2, help_text='Combined JAMB + Post-UTME score', max_digits=5, null=True)),
                ('o_level_results', models.JSONField(blank=True, default=dict)),
                ('waec_exam_no', models.CharField(blank=True, max_length=20)),
                ('neco_exam_no', models.CharField(blank=True, max_length=20)),
                ('meets_jamb_cutoff', models.BooleanField(blank=True, null=True)),
                ('meets_subject_reqs', models.BooleanField(blank=True, null=True)),
                ('meets_age_requirement', models.BooleanField(blank=True, null=True)),
                ('credentials_verified', models.BooleanField(default=False)),
                ('offered_at', models.DateTimeField(blank=True, null=True)),
                ('offer_expires_at', models.DateTimeField(blank=True, null=True)),
                ('offer_letter_sent', models.BooleanField(default=False)),
                ('applicant_response', models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('declined', 'Declined')], max_length=20)),
                ('response_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('screening_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'applications',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('JAMB_RESULT', 'JAMB Result'), ('WAEC_RESULT', 'WAEC Result'), ('NECO_RESULT', 'NECO Result'), ('BIRTH_CERT', 'Birth Certificate'), ('LGA_CERT', 'LGA Certificate'), ('PASSPORT', 'Passport Photograph'), ('MEDICAL_CERT', 'Medical Certificate'), ('OTHER', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='admissions/documents/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'application_documents',
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='admissions.application')),
            ],
            options={
                'db_table': 'application_status_history',
                'ordering': ['-timestamp'],
            },
        ),
    ]
