# Generated by Django 4.2.9 on 2026-05-16 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.application'),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='first_choice_dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_choice_applications', to='students.department'),
        ),
        migrations.AddField(
            model_name='application',
            name='linked_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='offered_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offered_applications', to='students.department'),
        ),
        migrations.AddField(
            model_name='application',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='second_choice_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_choice_applications', to='students.department'),
        ),
        migrations.AddField(
            model_name='application',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='admissions.admissionsession'),
        ),
        migrations.AddField(
            model_name='admissionoffer',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='admissions.application'),
        ),
        migrations.AddField(
            model_name='admissionoffer',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.department'),
        ),
        migrations.AddField(
            model_name='admissionoffer',
            name='issued_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='application_status_e61111_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['jamb_reg_no'], name='application_jamb_re_084110_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['email'], name='application_email_7bef0d_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['application_no'], name='application_applica_0eccbf_idx'),
        ),
    ]
