"""
FUGUSAU Portal — Reports App Models
Path: fugusau/apps/reports/models.py

Fix #9: reports/models.py was missing entirely.
Django didn't crash (no models = no DB tables), but the app config in
reports/apps.py emitted a startup warning and the admin panel showed nothing.

This file defines a ReportSnapshot model — a lightweight audit trail of
every generated report. It gives the admin panel something to display and
makes it possible to cache expensive report outputs.

If you don't need the audit trail right now you can leave the model empty
(just the class definition with `pass`), but including the snapshot is the
right foundation for the reports app.
"""
import uuid
from django.db import models
from django.conf import settings


class ReportSnapshot(models.Model):
    """
    Stores metadata (and optionally the output) of every generated report.
    Generated by the services in reports/services.py.
    """

    ENROLLMENT   = 'ENROLLMENT'
    RESULTS      = 'RESULTS'
    FEES         = 'FEES'
    ATTENDANCE   = 'ATTENDANCE'
    LIBRARY      = 'LIBRARY'
    HOSTEL       = 'HOSTEL'
    SECURITY     = 'SECURITY'
    ADMISSIONS   = 'ADMISSIONS'
    GENERAL      = 'GENERAL'

    REPORT_TYPE_CHOICES = [
        (ENROLLMENT, 'Enrollment Summary'),
        (RESULTS,    'Exam Results'),
        (FEES,       'Fee Collections'),
        (ATTENDANCE, 'Attendance'),
        (LIBRARY,    'Library Activity'),
        (HOSTEL,     'Hostel Occupancy'),
        (SECURITY,   'Security Events'),
        (ADMISSIONS, 'Admissions'),
        (GENERAL,    'General'),
    ]

    FORMAT_PDF  = 'pdf'
    FORMAT_CSV  = 'csv'
    FORMAT_XLSX = 'xlsx'
    FORMAT_JSON = 'json'

    FORMAT_CHOICES = [
        (FORMAT_PDF,  'PDF'),
        (FORMAT_CSV,  'CSV'),
        (FORMAT_XLSX, 'Excel'),
        (FORMAT_JSON, 'JSON'),
    ]

    id           = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    report_type  = models.CharField(max_length=30, choices=REPORT_TYPE_CHOICES)
    title        = models.CharField(max_length=255)
    generated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name='generated_reports',
    )
    parameters   = models.JSONField(
        default=dict,
        blank=True,
        help_text='The filter/date-range parameters used to produce this report',
    )
    file         = models.FileField(
        upload_to='reports/%Y/%m/',
        blank=True,
        null=True,
        help_text='Optional: stored output file (PDF/CSV/XLSX)',
    )
    output_format = models.CharField(
        max_length=10,
        choices=FORMAT_CHOICES,
        default=FORMAT_PDF,
    )
    row_count    = models.IntegerField(
        default=0,
        help_text='Number of data rows in this report snapshot',
    )
    generated_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'report_snapshots'
        ordering = ['-generated_at']
        verbose_name        = 'Report Snapshot'
        verbose_name_plural = 'Report Snapshots'

    def __str__(self):
        return f'{self.get_report_type_display()} — {self.generated_at:%d %b %Y %H:%M}'
