# Generated by Django 4.2.9 on 2026-05-16 14:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('mixed', 'Mixed')], max_length=10)),
                ('capacity', models.PositiveIntegerField()),
                ('amenities', models.JSONField(blank=True, default=list, help_text='["WiFi", "Water", "Generator"]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hostels',
            },
        ),
        migrations.CreateModel(
            name='HostelAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('vacated', 'Vacated')], default='pending', max_length=10)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('vacated_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'hostel_allocations',
                'ordering': ['-allocated_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=20)),
                ('capacity', models.PositiveIntegerField(default=4)),
                ('is_occupied', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostel.hostel')),
            ],
            options={
                'db_table': 'hostel_rooms',
            },
        ),
    ]
